import {INQUIRY_FIELDS,type InquiryField,type InstitutionInquiry} from '../../shared/institution-inquiry.js';
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const SECTIONS:{title:string;fields:InquiryField[]}[]=[
 {title:'Contact & institution',fields:['name','email','mobile','institution','role']},
 {title:'Project brief',fields:['project','audience','works','goals','rights']},
 {title:'Scope & timing',fields:['timeline','budget']},
];
/** Inline styles and presentation tables work across common email clients. */
export function inquiryEmail(data:InstitutionInquiry){
 const text=['New institutional inquiry for Adam','',...Object.entries(INQUIRY_FIELDS).map(([key,label])=>`${label}\n${data[key as InquiryField]||'Not provided'}\n`)].join('\n');
 const sections=SECTIONS.map(section=>`<tr><td style="padding:28px 32px 8px;font:700 12px Arial,sans-serif;letter-spacing:1.5px;text-transform:uppercase;color:#a6362b">${section.title}</td></tr>${section.fields.map(key=>`<tr><td style="padding:12px 32px;border-bottom:1px solid #e6e3dc"><div style="font:12px Arial,sans-serif;color:#6d6c68;margin-bottom:7px">${escape(INQUIRY_FIELDS[key])}</div><div style="font:16px/1.6 Arial,sans-serif;color:#121212;overflow-wrap:anywhere">${escape(data[key]||'Not provided').replace(/\r?\n/g,'<br>')}</div></td></tr>`).join('')}`).join('');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Adam institutional inquiry</title></head><body style="margin:0;padding:0;background:#f4f3ef"><div style="display:none;max-height:0;overflow:hidden">New project brief from ${escape(data.name)} at ${escape(data.institution)}.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f3ef"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #e6e3dc"><tr><td style="padding:32px;background:#121212;border-top:4px solid #c9473a"><div style="font:700 12px Arial,sans-serif;letter-spacing:3px;color:#f4f3ef">ADOMEH</div><h1 style="font:400 30px/1.2 Georgia,serif;color:#fff;margin:24px 0 12px">A new institutional inquiry.</h1><p style="font:16px/1.5 Arial,sans-serif;color:#dedbd4;margin:0">${escape(data.institution)}</p></td></tr>${sections}<tr><td style="padding:28px 32px"><a href="mailto:${escape(data.email)}" style="display:inline-block;background:#121212;color:#fff;padding:14px 22px;font:700 14px Arial,sans-serif;text-decoration:none">Reply to ${escape(data.name)}</a><p style="font:12px/1.6 Arial,sans-serif;color:#6d6c68;margin:18px 0 0">Sent from the Adam for institutions form. You can also reply directly to this email to contact the submitter.</p></td></tr></table></td></tr></table></body></html>`;
 return {text,html};
}

/** Confirmation goes to the submitter; replies go directly to Menachem. */
export function inquiryConfirmation(data:InstitutionInquiry){
 const text=`Thank you for reaching out to Adomeh.\n\nI've received your institutional inquiry and will review your project brief. I'll reach out to discuss your interests and the next steps.\n\nIf you'd like to add anything in the meantime, just reply to this email.\n\nBest,\nMenachem\nAdomeh`;
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>We received your inquiry</title></head><body style="margin:0;background:#f4f3ef"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #e6e3dc"><tr><td style="padding:32px;background:#121212;border-top:4px solid #c9473a"><p style="font:700 12px Arial,sans-serif;letter-spacing:3px;color:#fff;margin:0">ADOMEH</p><h1 style="font:400 32px/1.2 Georgia,serif;color:#fff;margin:24px 0 0">Thank you for reaching out.</h1></td></tr><tr><td style="padding:32px;font:16px/1.7 Arial,sans-serif;color:#121212"><p style="margin-top:0">Hello ${escape(data.name)},</p><p>I've received your institutional inquiry and will review your project brief. I'll reach out to discuss your interests and the next steps.</p><p>If you'd like to add anything in the meantime, just reply to this email.</p><p style="margin-bottom:0">Best,<br><strong>Menachem</strong><br><span style="color:#6d6c68">Adomeh</span></p></td></tr></table></td></tr></table></body></html>`;
 return {text,html};
}
