// Generated by scripts/build-corpus-index.mjs from the local corpora under content/. Do not edit by hand.
import type {Work} from './study';
export const CORPUS_WORKS:Work[]=[
 {
  id: "hippocrates-01-de-prisca-medicina",
  author: "hippocrates",
  number: 1,
  title: "On Ancient Medicine (De prisca medicina)",
  dir: "hippocrates/01-de-prisca-medicina",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng3.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "eng-perseus-eng4.md",
    title: "English · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, translator. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De prisca medicina 1839",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 1. Littré, Émile, editor. Paris: Baillière, 1839.",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-02-de-aere-aquis-locis",
  author: "hippocrates",
  number: 2,
  title: "Airs, Waters, Places (De aere, aquis, locis)",
  dir: "hippocrates/02-de-aere-aquis-locis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng3.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "eng-perseus-eng4.md",
    title: "English · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, translator. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De aere, aquis, locis 1840",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 2. Littré, Émile, editor. Paris: Baillière, 1840",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-03-prognosticon",
  author: "hippocrates",
  number: 3,
  title: "Prognostic (Prognosticon)",
  dir: "hippocrates/03-prognosticon",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Prognosticon 1840",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 2. Littré, Émile, editor. Paris: Baillière, 1840",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Προγνωστικόν 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 2. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-04-de-diaeta-in-morbis-acutis",
  author: "hippocrates",
  number: 4,
  title: "Regimen in Acute Diseases (De diaeta in morbis acutis)",
  dir: "hippocrates/04-de-diaeta-in-morbis-acutis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De diaeta in morbis acutis 1840",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 2. Littré, Émile, editor. Paris: Baillière, 1840",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ διαίτης ὀξέων 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 2. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-05-de-diaeta-acutorum-spurium",
  author: "hippocrates",
  number: 5,
  title: "Regimen in Acute Diseases (Appendix) (De diaeta acutorum (spurium))",
  dir: "hippocrates/05-de-diaeta-acutorum-spurium",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De diaeta acutorum (spurium) 1840",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 2. Littré, Émile, editor. Paris: Baillière, 1840",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ διαίτης ὀξέων. Νόθα 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 2. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-06-epidemiarum",
  author: "hippocrates",
  number: 6,
  title: "Epidemics (Epidemiarum)",
  dir: "hippocrates/06-epidemiarum",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng3.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "eng-perseus-eng4.md",
    title: "English · Epidemics 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Epidemiarum 1840",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 2. Littré, Émile, editor. Paris: Baillière, 1840",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-07-de-capitis-vulneribus",
  author: "hippocrates",
  number: 7,
  title: "On Wounds in the Head (De capitis vulneribus)",
  dir: "hippocrates/07-de-capitis-vulneribus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De capitis vulneribus 1841",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 3. Littré, Émile, editor. Paris: Baillière, 1841",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ τῶν ἐν κεφαλῇ τρωμάτων 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 3. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-08-de-officina-medici",
  author: "hippocrates",
  number: 8,
  title: "In the Surgery (De officina medici)",
  dir: "hippocrates/08-de-officina-medici",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De officina medici 1841",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 3. Littré, Émile, editor. Paris: Baillière, 1841",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Κατ’ ἰητρεῖον 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 3. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-09-de-fracturis",
  author: "hippocrates",
  number: 9,
  title: "On Fractures (De fracturis)",
  dir: "hippocrates/09-de-fracturis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De fracturis 1841",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 3. Littré, Émile, editor. Paris: Baillière, 1841",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ ἀγμῶν 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 3. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-10-de-articulis",
  author: "hippocrates",
  number: 10,
  title: "On Joints (De articulis)",
  dir: "hippocrates/10-de-articulis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De articulis 1844",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 4. Littré, Émile, editor. Paris: Baillière, 1844",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ ἄρθρων 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 4. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-11-vectiarius",
  author: "hippocrates",
  number: 11,
  title: "Instruments of Reduction (Vectiarius)",
  dir: "hippocrates/11-vectiarius",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Vectiarius 1844",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 4. Littré, Émile, editor. Paris: Baillière, 1844",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Μοχλικός 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 4. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-12-aphorismi",
  author: "hippocrates",
  number: 12,
  title: "Aphorisms (Aphorismi)",
  dir: "hippocrates/12-aphorismi",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Aphorismi 1844",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 4. Littré, Émile, editor. Paris: Baillière, 1844",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Ἀφορισμοί 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 4. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-13-iusiurandum",
  author: "hippocrates",
  number: 13,
  title: "The Oath (Iusiurandum)",
  dir: "hippocrates/13-iusiurandum",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng4.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "eng-perseus-eng5.md",
    title: "English · Oath 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Iusiurandum 1844",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 4. Littré, Émile, editor. Paris: Baillière, 1844",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-14-lex",
  author: "hippocrates",
  number: 14,
  title: "The Law (Lex)",
  dir: "hippocrates/14-lex",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Lex 1844",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 4. Littré, Émile, editor. Paris: Baillière, 1844",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-15-de-humoribus",
  author: "hippocrates",
  number: 15,
  title: "On Humours (De humoribus)",
  dir: "hippocrates/15-de-humoribus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De humoribus 1846",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 5. Littré, Émile, editor. Paris: Baillière, 1846",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-16-prorrheticon-i",
  author: "hippocrates",
  number: 16,
  title: "Prorrhetic I (Prorrheticon I)",
  dir: "hippocrates/16-prorrheticon-i",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Prorrheticon I 1846",
    subtitle: "Hippocrates, Prorrheticon I, Oeuvres complètes, Littré, Volume 5, 1846",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-17-coa-praesagia",
  author: "hippocrates",
  number: 17,
  title: "Coan Prognoses (Coa praesagia)",
  dir: "hippocrates/17-coa-praesagia",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Coa praesagia 1846",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 5. Littré, Émile, editor. Paris: Baillière, 1846",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-18-de-arte",
  author: "hippocrates",
  number: 18,
  title: "On the Art (De arte)",
  dir: "hippocrates/18-de-arte",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De arte 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-19-de-natura-hominis",
  author: "hippocrates",
  number: 19,
  title: "On the Nature of Man (De natura hominis)",
  dir: "hippocrates/19-de-natura-hominis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De natura hominis 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-20-de-salubri-diaeta",
  author: "hippocrates",
  number: 20,
  title: "Regimen in Health (De salubri diaeta)",
  dir: "hippocrates/20-de-salubri-diaeta",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De salubri diaeta 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-21-de-flatibus",
  author: "hippocrates",
  number: 21,
  title: "On Breaths (De flatibus)",
  dir: "hippocrates/21-de-flatibus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De flatibus 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-22-de-liquidorum-usu",
  author: "hippocrates",
  number: 22,
  title: "On the Use of Liquids (De liquidorum usu)",
  dir: "hippocrates/22-de-liquidorum-usu",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De liquidorum usu 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-23-de-morbis-i-iii",
  author: "hippocrates",
  number: 23,
  title: "On Diseases I–III (De morbis i-iii)",
  dir: "hippocrates/23-de-morbis-i-iii",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De morbis i-iii 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6-7. Littré, Émile, editor. Paris: Baillière, 1849-1851.",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-24-de-affectionibus",
  author: "hippocrates",
  number: 24,
  title: "On Affections (De affectionibus)",
  dir: "hippocrates/24-de-affectionibus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De affectionibus 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-25-de-locis-in-homine",
  author: "hippocrates",
  number: 25,
  title: "On Places in Man (De locis in homine)",
  dir: "hippocrates/25-de-locis-in-homine",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De locis in homine 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-26-de-morbo-sacro",
  author: "hippocrates",
  number: 26,
  title: "On the Sacred Disease (De morbo sacro)",
  dir: "hippocrates/26-de-morbo-sacro",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De morbo sacro 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ ἱερῆς νούσου 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 6. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-27-de-ulceribus",
  author: "hippocrates",
  number: 27,
  title: "On Ulcers (De ulceribus)",
  dir: "hippocrates/27-de-ulceribus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De ulceribus 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ ἑλκῶν 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 6. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-28-de-haemorrhoidibus",
  author: "hippocrates",
  number: 28,
  title: "On Haemorrhoids (De haemorrhoidibus)",
  dir: "hippocrates/28-de-haemorrhoidibus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De haemorrhoidibus 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ αἱμοῤῥοίδων 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 6. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-29-de-fistulis",
  author: "hippocrates",
  number: 29,
  title: "On Fistulas (De fistulis)",
  dir: "hippocrates/29-de-fistulis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Francis 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De fistulis 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · Περὶ συρίγγων 1961",
    subtitle: "Hippocrates. Oeuvres complètes d’Hippocrate, Vol. 6. Littré, Émile, editor. Adolf M. Hakkert: Amsterdam, 1961 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-30-de-diaeta",
  author: "hippocrates",
  number: 30,
  title: "On Regimen (De diaeta)",
  dir: "hippocrates/30-de-diaeta",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De diaeta 1849",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 6. Littré, Émile, editor. Paris: Baillière, 1849",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-31-de-affectionibus-interioribus",
  author: "hippocrates",
  number: 31,
  title: "On Internal Affections (De affectionibus interioribus)",
  dir: "hippocrates/31-de-affectionibus-interioribus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De affectionibus interioribus 1851",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 7. Littré, Émile, editor. Paris: Baillière, 1851",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-32-de-natura-muliebri",
  author: "hippocrates",
  number: 32,
  title: "On the Nature of Women (De natura muliebri)",
  dir: "hippocrates/32-de-natura-muliebri",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De natura muliebri 1851",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 7. Littré, Émile, editor. Paris: Baillière, 1851",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-33-de-octimestri-partu",
  author: "hippocrates",
  number: 33,
  title: "On the Eight-Months’ Child (De octimestri partu)",
  dir: "hippocrates/33-de-octimestri-partu",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De octimestri partu 1851",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 7. Littré, Émile, editor. Paris: Baillière, 1851",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-34-de-muliebribus",
  author: "hippocrates",
  number: 34,
  title: "Diseases of Women (De muliebribus)",
  dir: "hippocrates/34-de-muliebribus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De muliebribus 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-35-de-virginum-morbis",
  author: "hippocrates",
  number: 35,
  title: "On the Diseases of Girls (De virginum morbis)",
  dir: "hippocrates/35-de-virginum-morbis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De virginum morbis 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-36-de-superfoetatione",
  author: "hippocrates",
  number: 36,
  title: "On Superfetation (De superfoetatione)",
  dir: "hippocrates/36-de-superfoetatione",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De superfoetatione 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-37-de-exsectione-foetus",
  author: "hippocrates",
  number: 37,
  title: "On the Excision of the Fetus (De exsectione foetus)",
  dir: "hippocrates/37-de-exsectione-foetus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De exsectione foetus 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-38-de-anatomia",
  author: "hippocrates",
  number: 38,
  title: "On Anatomy (De anatomia)",
  dir: "hippocrates/38-de-anatomia",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De anatomia 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-39-de-dentitione",
  author: "hippocrates",
  number: 39,
  title: "On Dentition (De dentitione)",
  dir: "hippocrates/39-de-dentitione",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De dentitione 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-40-de-glandulis",
  author: "hippocrates",
  number: 40,
  title: "On Glands (De glandulis)",
  dir: "hippocrates/40-de-glandulis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De glandulis 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-41-de-carnibus",
  author: "hippocrates",
  number: 41,
  title: "On Fleshes (De carnibus)",
  dir: "hippocrates/41-de-carnibus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De carnibus 1853",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 8. Littré, Émile, editor. Paris: Baillière, 1853",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-42-de-corde",
  author: "hippocrates",
  number: 42,
  title: "On the Heart (De corde)",
  dir: "hippocrates/42-de-corde",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De corde 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-43-de-alimento",
  author: "hippocrates",
  number: 43,
  title: "On Nutriment (De alimento)",
  dir: "hippocrates/43-de-alimento",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Nutriment 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De alimento 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-44-de-visu",
  author: "hippocrates",
  number: 44,
  title: "On Sight (De visu)",
  dir: "hippocrates/44-de-visu",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De visu 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-45-de-natura-ossium",
  author: "hippocrates",
  number: 45,
  title: "On the Nature of Bones (De natura ossium)",
  dir: "hippocrates/45-de-natura-ossium",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De natura ossium 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-46-de-medico",
  author: "hippocrates",
  number: 46,
  title: "On the Physician (De medico)",
  dir: "hippocrates/46-de-medico",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De medico 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-47-de-habitu-decenti",
  author: "hippocrates",
  number: 47,
  title: "On Decorum (De habitu decenti)",
  dir: "hippocrates/47-de-habitu-decenti",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De habitu decenti 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-48-praeceptiones",
  author: "hippocrates",
  number: 48,
  title: "Precepts (Praeceptiones)",
  dir: "hippocrates/48-praeceptiones",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Precepts 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Praeceptiones 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   },
   {
    file: "grc-perseus-grc2.md",
    title: "Greek · William Henry Samuel 1923",
    subtitle: "Hippocrates, Vol. 1. Jones, William Henry Samuel, editor. London: William Heinemann Ltd.; Cambridge, MA: Harvard University Press, 1923 (printing).",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-49-de-crisibus",
  author: "hippocrates",
  number: 49,
  title: "On Crises (De crisibus)",
  dir: "hippocrates/49-de-crisibus",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De crisibus 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-50-de-diebus-criticis",
  author: "hippocrates",
  number: 50,
  title: "On Critical Days (De diebus criticis)",
  dir: "hippocrates/50-de-diebus-criticis",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · De diebus criticis 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 },
 {
  id: "hippocrates-51-epistulae-decretum-orationes",
  author: "hippocrates",
  number: 51,
  title: "Letters, Decree, Speeches (Epistulae, Decretum, Orationes)",
  dir: "hippocrates/51-epistulae-decretum-orationes",
  source: "Perseus canonical-greekLit / First1KGreek (CC-BY-SA-4.0); Claude translations from the Greek",
  chapters: [
   {
    file: "eng-claude.md",
    title: "English · Claude, from the Greek (machine translation)",
    subtitle: "Rendered from the Greek in this repository; citation anchors preserved. Reading aid, not a scholarly edition.",
    lang: "eng"
   },
   {
    file: "grc-1st1k-grc1.md",
    title: "Greek · Epistulae, Decretum, Orationes 1861",
    subtitle: "Hippocrates. Oeuvres complètes d'Hippocrate, Vol. 9. Littré, Émile, editor. Paris: Baillière, 1861",
    lang: "grc"
   }
  ]
 }
];
