// Generated by scripts/build-corpus-index.mjs from the local corpora under content/. Do not edit by hand.
import {withTiers,type Work} from './study.ts';
export const CORPUS_WORKS:Work[]=withTiers([
 {
  id: "hippocrates-01-de-prisca-medicina",
  author: "hippocrates",
  number: 1,
  title: "On Ancient Medicine",
  dir: "hippocrates/01-de-prisca-medicina",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng3.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-02-de-aere-aquis-locis",
  author: "hippocrates",
  number: 2,
  title: "Airs, Waters, Places",
  dir: "hippocrates/02-de-aere-aquis-locis",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng3.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-03-prognosticon",
  author: "hippocrates",
  number: 3,
  title: "Prognostic",
  dir: "hippocrates/03-prognosticon",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-04-de-diaeta-in-morbis-acutis",
  author: "hippocrates",
  number: 4,
  title: "Regimen in Acute Diseases",
  dir: "hippocrates/04-de-diaeta-in-morbis-acutis",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-06-epidemiarum",
  author: "hippocrates",
  number: 5,
  title: "Epidemics",
  dir: "hippocrates/06-epidemiarum",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng3.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-07-de-capitis-vulneribus",
  author: "hippocrates",
  number: 6,
  title: "On Wounds in the Head",
  dir: "hippocrates/07-de-capitis-vulneribus",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 1. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-08-de-officina-medici",
  author: "hippocrates",
  number: 7,
  title: "In the Surgery",
  dir: "hippocrates/08-de-officina-medici",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-09-de-fracturis",
  author: "hippocrates",
  number: 8,
  title: "On Fractures",
  dir: "hippocrates/09-de-fracturis",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-10-de-articulis",
  author: "hippocrates",
  number: 9,
  title: "On Joints",
  dir: "hippocrates/10-de-articulis",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-11-vectiarius",
  author: "hippocrates",
  number: 10,
  title: "Instruments of Reduction",
  dir: "hippocrates/11-vectiarius",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-12-aphorismi",
  author: "hippocrates",
  number: 11,
  title: "Aphorisms",
  dir: "hippocrates/12-aphorismi",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-13-iusiurandum",
  author: "hippocrates",
  number: 12,
  title: "The Oath",
  dir: "hippocrates/13-iusiurandum",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng4.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-14-lex",
  author: "hippocrates",
  number: 13,
  title: "The Law",
  dir: "hippocrates/14-lex",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-26-de-morbo-sacro",
  author: "hippocrates",
  number: 14,
  title: "On the Sacred Disease",
  dir: "hippocrates/26-de-morbo-sacro",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-27-de-ulceribus",
  author: "hippocrates",
  number: 15,
  title: "On Ulcers",
  dir: "hippocrates/27-de-ulceribus",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-28-de-haemorrhoidibus",
  author: "hippocrates",
  number: 16,
  title: "On Haemorrhoids",
  dir: "hippocrates/28-de-haemorrhoidibus",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "hippocrates-29-de-fistulis",
  author: "hippocrates",
  number: 17,
  title: "On Fistulas",
  dir: "hippocrates/29-de-fistulis",
  source: "Francis Adams, The Genuine Works of Hippocrates (London 1849; New York 1886), public domain",
  chapters: [
   {
    file: "eng-perseus-eng2.md",
    title: "English · Adams 1886",
    subtitle: "Hippocrates, The Genuine Works of Hippocrates, Vol. 2. Adams, Francis, translator. New York: William Wood and Company, 1886.",
    lang: "eng"
   }
  ]
 },
 {
  id: "avicenna-01-canon-book-1",
  author: "avicenna",
  number: 1,
  title: "The Canon of Medicine, Book I",
  dir: "avicenna/01-canon-book-1",
  source: "Machine translation from the Arabic by Adomeh (Claude), CC BY-SA 4.0; Arabic text: Arabic and Latin Corpus, ed. D. N. Hasse, University of Würzburg (CC BY-SA 4.0)",
  chapters: [
   {
    file: "eng-00.md",
    title: "Author's preface",
    subtitle: "The Canon, 1",
    lang: "eng"
   },
   {
    file: "eng-101.md",
    title: "Part 1, Lesson 1: The definition and subject-matter of medicine",
    subtitle: "The Canon, 1.1.1",
    lang: "eng"
   },
   {
    file: "eng-102.md",
    title: "Part 1, Lesson 2: The elements",
    subtitle: "The Canon, 1.1.2",
    lang: "eng"
   },
   {
    file: "eng-103.md",
    title: "Part 1, Lesson 3: Temperaments",
    subtitle: "The Canon, 1.1.3",
    lang: "eng"
   },
   {
    file: "eng-104.md",
    title: "Part 1, Lesson 4: The humours",
    subtitle: "The Canon, 1.1.4",
    lang: "eng"
   },
   {
    file: "eng-105.md",
    title: "Part 1, Lesson 5: The organs (anatomy)",
    subtitle: "The Canon, 1.1.5",
    lang: "eng"
   },
   {
    file: "eng-106.md",
    title: "Part 1, Lesson 6: The faculties and their actions",
    subtitle: "The Canon, 1.1.6",
    lang: "eng"
   },
   {
    file: "eng-201.md",
    title: "Part 2, Lesson 1: Diseases",
    subtitle: "The Canon, 1.2.1",
    lang: "eng"
   },
   {
    file: "eng-202.md",
    title: "Part 2, Lesson 2: Causes",
    subtitle: "The Canon, 1.2.2",
    lang: "eng"
   },
   {
    file: "eng-203.md",
    title: "Part 2, Lesson 3: Symptoms and signs",
    subtitle: "The Canon, 1.2.3",
    lang: "eng"
   },
   {
    file: "eng-301.md",
    title: "Part 3: The cause of health and disease, and the necessity of death",
    subtitle: "The Canon, 1.3.1",
    lang: "eng"
   },
   {
    file: "eng-302.md",
    title: "Part 3, Lesson 1: Upbringing",
    subtitle: "The Canon, 1.3.2",
    lang: "eng"
   },
   {
    file: "eng-303.md",
    title: "Part 3, Lesson 2: The regimen of adults",
    subtitle: "The Canon, 1.3.3",
    lang: "eng"
   },
   {
    file: "eng-304.md",
    title: "Part 3, Lesson 3: The regimen of the old",
    subtitle: "The Canon, 1.3.4",
    lang: "eng"
   },
   {
    file: "eng-305.md",
    title: "Part 3, Lesson 4: The regimen of unbalanced temperaments",
    subtitle: "The Canon, 1.3.5",
    lang: "eng"
   },
   {
    file: "eng-306.md",
    title: "Part 3, Lesson 5: Changes (seasons and travel)",
    subtitle: "The Canon, 1.3.6",
    lang: "eng"
   },
   {
    file: "eng-400.md",
    title: "Part 4: The kinds of treatment",
    subtitle: "The Canon, 1.4",
    lang: "eng"
   }
  ]
 },
 {
  id: "avicenna-02-canon-book-2",
  author: "avicenna",
  number: 2,
  title: "The Canon of Medicine, Book II",
  dir: "avicenna/02-canon-book-2",
  source: "Machine translation from the Arabic by Adomeh (Claude), CC BY-SA 4.0; Arabic text: Arabic and Latin Corpus, ed. D. N. Hasse, University of Würzburg (CC BY-SA 4.0)",
  chapters: [
   {
    file: "eng-100.md",
    title: "Treatise 1: General rules on simple drugs",
    subtitle: "The Canon, 2.1",
    lang: "eng"
   },
   {
    file: "eng-200.md",
    title: "Treatise 2: The tables of actions",
    subtitle: "The Canon, 2.2",
    lang: "eng"
   },
   {
    file: "eng-201.md",
    title: "Simple drugs: Alif (ا)",
    subtitle: "The Canon, 2.2.14.2.1",
    lang: "eng"
   },
   {
    file: "eng-202.md",
    title: "Simple drugs: Bāʾ (ب)",
    subtitle: "The Canon, 2.2.14.2.2",
    lang: "eng"
   },
   {
    file: "eng-203.md",
    title: "Simple drugs: Tāʾ (ت)",
    subtitle: "The Canon, 2.2.14.2.3",
    lang: "eng"
   },
   {
    file: "eng-204.md",
    title: "Simple drugs: Thāʾ (ث)",
    subtitle: "The Canon, 2.2.14.2.4",
    lang: "eng"
   },
   {
    file: "eng-205.md",
    title: "Simple drugs: Jīm (ج)",
    subtitle: "The Canon, 2.2.14.2.5",
    lang: "eng"
   },
   {
    file: "eng-206.md",
    title: "Simple drugs: Ḥāʾ (ح)",
    subtitle: "The Canon, 2.2.14.2.6",
    lang: "eng"
   },
   {
    file: "eng-207.md",
    title: "Simple drugs: Khāʾ (خ)",
    subtitle: "The Canon, 2.2.14.2.7",
    lang: "eng"
   },
   {
    file: "eng-208.md",
    title: "Simple drugs: Dāl (د)",
    subtitle: "The Canon, 2.2.14.2.8",
    lang: "eng"
   },
   {
    file: "eng-209.md",
    title: "Simple drugs: Dhāl (ذ)",
    subtitle: "The Canon, 2.2.14.2.9",
    lang: "eng"
   },
   {
    file: "eng-210.md",
    title: "Simple drugs: Rāʾ (ر)",
    subtitle: "The Canon, 2.2.14.2.10",
    lang: "eng"
   },
   {
    file: "eng-211.md",
    title: "Simple drugs: Zāy (ز)",
    subtitle: "The Canon, 2.2.14.2.11",
    lang: "eng"
   },
   {
    file: "eng-212.md",
    title: "Simple drugs: Sīn (س)",
    subtitle: "The Canon, 2.2.14.2.12",
    lang: "eng"
   },
   {
    file: "eng-213.md",
    title: "Simple drugs: Shīn (ش)",
    subtitle: "The Canon, 2.2.14.2.13",
    lang: "eng"
   },
   {
    file: "eng-214.md",
    title: "Simple drugs: Ṣād (ص)",
    subtitle: "The Canon, 2.2.14.2.14",
    lang: "eng"
   },
   {
    file: "eng-215.md",
    title: "Simple drugs: Ḍād (ض)",
    subtitle: "The Canon, 2.2.14.2.15",
    lang: "eng"
   },
   {
    file: "eng-216.md",
    title: "Simple drugs: Ṭāʾ (ط)",
    subtitle: "The Canon, 2.2.14.2.16",
    lang: "eng"
   },
   {
    file: "eng-217.md",
    title: "Simple drugs: Ẓāʾ and ʿAyn (ظ ع)",
    subtitle: "The Canon, 2.2.14.2.17",
    lang: "eng"
   },
   {
    file: "eng-218.md",
    title: "Simple drugs: Ghayn (غ)",
    subtitle: "The Canon, 2.2.14.2.18",
    lang: "eng"
   },
   {
    file: "eng-219.md",
    title: "Simple drugs: Fāʾ (ف)",
    subtitle: "The Canon, 2.2.14.2.19",
    lang: "eng"
   },
   {
    file: "eng-220.md",
    title: "Simple drugs: Qāf (ق)",
    subtitle: "The Canon, 2.2.14.2.20",
    lang: "eng"
   },
   {
    file: "eng-221.md",
    title: "Simple drugs: Kāf (ك)",
    subtitle: "The Canon, 2.2.14.2.21",
    lang: "eng"
   },
   {
    file: "eng-222.md",
    title: "Simple drugs: Lām (ل)",
    subtitle: "The Canon, 2.2.14.2.22",
    lang: "eng"
   },
   {
    file: "eng-223.md",
    title: "Simple drugs: Mīm (م)",
    subtitle: "The Canon, 2.2.14.2.23",
    lang: "eng"
   },
   {
    file: "eng-224.md",
    title: "Simple drugs: Nūn (ن)",
    subtitle: "The Canon, 2.2.14.2.24",
    lang: "eng"
   },
   {
    file: "eng-225.md",
    title: "Simple drugs: Wāw (و)",
    subtitle: "The Canon, 2.2.14.2.25",
    lang: "eng"
   },
   {
    file: "eng-226.md",
    title: "Simple drugs: Hāʾ (ه)",
    subtitle: "The Canon, 2.2.14.2.26",
    lang: "eng"
   },
   {
    file: "eng-227.md",
    title: "Simple drugs: Yāʾ (ي)",
    subtitle: "The Canon, 2.2.14.2.27",
    lang: "eng"
   }
  ]
 },
 {
  id: "avicenna-03-canon-book-3",
  author: "avicenna",
  number: 3,
  title: "The Canon of Medicine, Book III",
  dir: "avicenna/03-canon-book-3",
  source: "Machine translation from the Arabic by Adomeh (Claude), CC BY-SA 4.0; Arabic text: Arabic and Latin Corpus, ed. D. N. Hasse, University of Würzburg (CC BY-SA 4.0)",
  chapters: [
   {
    file: "eng-100.md",
    title: "The first treatise: on the general [rules of the] diseases of the head and the brain",
    subtitle: "The Canon, 3.1",
    lang: "eng"
   },
   {
    file: "eng-200.md",
    title: "On the diseases of the nerves; it is a single treatise",
    subtitle: "The Canon, 3.2",
    lang: "eng"
   },
   {
    file: "eng-300.md",
    title: "[The first treatise: a general statement on the first principles of the states of the eye, and on ophthalmia]",
    subtitle: "The Canon, 3.3",
    lang: "eng"
   },
   {
    file: "eng-400.md",
    title: "It is a single treatise",
    subtitle: "The Canon, 3.4",
    lang: "eng"
   },
   {
    file: "eng-500.md",
    title: "The first treatise: on smell, its harms, and the flows",
    subtitle: "The Canon, 3.5",
    lang: "eng"
   },
   {
    file: "eng-600.md",
    title: "Chapter on the [anatomy of the] mouth and tongue",
    subtitle: "The Canon, 3.6",
    lang: "eng"
   },
   {
    file: "eng-700.md",
    title: "Chapter: a ⟨general⟩ statement on the teeth",
    subtitle: "The Canon, 3.7",
    lang: "eng"
   },
   {
    file: "eng-800.md",
    title: "Chapter on the diseases of the gums",
    subtitle: "The Canon, 3.8",
    lang: "eng"
   },
   {
    file: "eng-900.md",
    title: "Chapter on the anatomy of the members of the throat",
    subtitle: "The Canon, 3.9",
    lang: "eng"
   },
   {
    file: "eng-1000.md",
    title: "Its first treatise: on voices and on breathing",
    subtitle: "The Canon, 3.10",
    lang: "eng"
   },
   {
    file: "eng-1100.md",
    title: "Its first treatise: on principles and foundations for that",
    subtitle: "The Canon, 3.11",
    lang: "eng"
   },
   {
    file: "eng-1200.md",
    title: "Chapter on the anatomy of the breast",
    subtitle: "The Canon, 3.12",
    lang: "eng"
   },
   {
    file: "eng-1300.md",
    title: "Its first treatise: on the conditions of the gullet ⟨and the stomach⟩, and on principles of the matter of the stomach",
    subtitle: "The Canon, 3.13",
    lang: "eng"
   },
   {
    file: "eng-1400.md",
    title: "The first treatise: on the generalities of the conditions of the liver",
    subtitle: "The Canon, 3.14",
    lang: "eng"
   },
   {
    file: "eng-1500.md",
    title: "On the states of the gall bladder and the spleen, and it is two treatises. The first treatise: on the anatomy of the gall bladder and the spleen, and on jaundice",
    subtitle: "The Canon, 3.15",
    lang: "eng"
   },
   {
    file: "eng-1600.md",
    title: "The first treatise: on their anatomy and on looseness in general",
    subtitle: "The Canon, 3.16",
    lang: "eng"
   },
   {
    file: "eng-1700.md",
    title: "On the disorders of the anus, and it is one treatise",
    subtitle: "The Canon, 3.17",
    lang: "eng"
   },
   {
    file: "eng-1800.md",
    title: "The first treatise: on the general rulings on the kidney, and on their detail",
    subtitle: "The Canon, 3.18",
    lang: "eng"
   },
   {
    file: "eng-1900.md",
    title: "The first treatise: on the states of the bladder",
    subtitle: "The Canon, 3.19",
    lang: "eng"
   },
   {
    file: "eng-2000.md",
    title: "The first treatise: on the general matters and on venery (bāh)",
    subtitle: "The Canon, 3.20",
    lang: "eng"
   },
   {
    file: "eng-2100.md",
    title: "The first treatise: on the principles, on conception, and on delivery",
    subtitle: "The Canon, 3.21",
    lang: "eng"
   },
   {
    file: "eng-2200.md",
    title: "The first treatise: on what befalls them of damages of size ⟨and position, and it is nine chapters⟩. The first: on the form of the omentum and the two membranes",
    subtitle: "The Canon, 3.22",
    lang: "eng"
   }
  ]
 }
]);
