import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,BookOpen,ChevronDown,ChevronLeft,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import Reader from './reader';
import {classical} from './classical';
import {CORPUS_WORKS} from './corpus';
import {AUTHORS,MAIMONIDES_WORKS,chapterUrl,lessonFor,workForUrl,type Lesson,type Work} from './study';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
type Panel='layers'|'search'|'study'|null;
interface Reading {work:Work;file:string}
const WORKS:Work[]=[...MAIMONIDES_WORKS,...CORPUS_WORKS];
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],secondary:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<Panel>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const [reading,setReading]=useState<Reading|null>(null),[openWork,setOpenWork]=useState<string|null>('maimonides-asthma'),[focusNote,setFocusNote]=useState<{term:string;concepts:Concept[]}|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const byName=useMemo(()=>new Map(atlas?.concepts.map(c=>[c.name,c])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setFocusNote(null);setState(s=>({...s,selected:c.elements,secondary:[],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setFocusNote(null);setState(s=>({...s,selected:[id],secondary:[],isolate:false,rotate:false}));setDetails(true);if(panel!=='study')setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],secondary:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setFocusNote(null);setDetails(false);setPanel(null);};
 const openPanel=(next:Exclude<Panel,null>)=>{setDetails(false);setPanel(p=>p===next?null:next);};

 // Study layer: a chapter of a classical text, its mapped anatomy, and live terms in the reading pane.
 const lesson=reading?lessonFor(reading.work.id,reading.file):null;
 const chapterIndex=reading?reading.work.chapters.findIndex(c=>c.file===reading.file):-1;
 const chapter=reading&&chapterIndex>=0?reading.work.chapters[chapterIndex]:null;
 const elementsOf=(names:string[])=>[...new Set(names.flatMap(n=>byName.get(n)?.elements??[]))];
 const applyLesson=(l:Lesson)=>{const primary=elementsOf(l.focus.filter(f=>f.role==='primary').flatMap(f=>f.concepts)),primarySet=new Set(primary);const secondary=elementsOf(l.focus.filter(f=>f.role==='secondary').flatMap(f=>f.concepts)).filter(id=>!primarySet.has(id));setState(s=>({...s,selected:[...primary,...secondary],secondary,isolate:false,rotate:false,explode:0,visible:l.systems??s.visible,view:l.view??s.view,reset:s.reset+1}));};
 const openChapter=(work:Work,file:string)=>{setReading({work,file});setFocusNote(null);setDetails(false);setChosen(null);setOpenWork(work.id);setPanel(innerWidth<768?null:'study');const l=lessonFor(work.id,file);if(l)applyLesson(l);else setState(s=>({...s,selected:[],secondary:[],isolate:false}));};
 const closeReader=()=>{setReading(null);setFocusNote(null);setState(s=>({...s,selected:[],secondary:[],isolate:false}));};
 const go=(d:number)=>{if(!reading||chapterIndex<0)return;const next=reading.work.chapters[chapterIndex+d];if(next)openChapter(reading.work,next.file);};
 const onNavigate=(url:string)=>{const hit=workForUrl(url,WORKS);if(hit)openChapter(hit.work,hit.file);};
 const onTerm=(term:string,names:string[])=>{const concepts=names.map(n=>byName.get(n)).filter((c):c is Concept=>!!c);if(!concepts.length)return;const primary=[...new Set(concepts.flatMap(c=>c.elements))],primarySet=new Set(primary);const context=lesson?elementsOf(lesson.focus.flatMap(f=>f.concepts)).filter(id=>!primarySet.has(id)):[];setState(s=>({...s,selected:[...primary,...context],secondary:context,isolate:false,rotate:false}));setFocusNote({term,concepts});setDetails(false);};
 const author=reading?AUTHORS.find(a=>a.id===reading.work.author):null;
 const chosenNote=chosen?classical(chosen.name):undefined;

 return <main className={`studio ${reading?'reading':''} ${panel==='study'?'studying':''}`}>
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> ANATOMY FOR THE CLASSICAL PHYSICIANS</div><h1>Adam<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} modeled pieces <span>·</span> BodyParts3D <span>·</span> Maimonides · Hippocrates · Galen · Avicenna</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='study'?'active':''} onClick={()=>openPanel('study')} aria-label="Open the study library"><BookOpen size={18}/><span>Study</span></Button><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="About Adam" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],secondary:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],secondary:[],isolate:false,visible:['skeletal']}))}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],secondary:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Organs</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[],secondary:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],secondary:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='study'&&<section className="study-panel glass mobile-open" aria-label="Study library">
   <div className="panel-heading"><span>Study</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close study"><X size={18}/></Button></div>
   <div className="study-list">{AUTHORS.map(a=>{const works=WORKS.filter(w=>w.author===a.id);return <div className="author-group" key={a.id}><h3>{a.name}<span>{a.dates}</span></h3>{works.length===0&&<p className="study-note">{a.note}</p>}{works.map(w=><div key={w.id}><Button variant="ghost" className={`work-title ${openWork===w.id?'open':''}`} onClick={()=>setOpenWork(openWork===w.id?null:w.id)} aria-expanded={openWork===w.id}><ChevronDown size={14} className="work-chevron"/><span className="work-name">{w.number?`${w.number}. `:''}{w.title}</span><small>{w.chapters.length}</small></Button>{openWork===w.id&&<div className="chapter-list">{w.chapters.map(ch=>{const active=reading?.work.id===w.id&&reading.file===ch.file;return <button type="button" key={ch.file} className={`chapter ${active?'active':''} ${lessonFor(w.id,ch.file)?'mapped':''}`} onClick={()=>openChapter(w,ch.file)}><span>{ch.title}</span>{ch.subtitle&&<small>{ch.subtitle}</small>}</button>;})}</div>}</div>)}</div>;})}</div>
   <div className="panel-foot"><span><i className="focus-dot primary inline"/> chapter mapped to the body</span></div>
  </section>}
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??focusNote?.term??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':reading&&chapter?`${reading.work.title} · ${chapter.title}`.toUpperCase():'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'Drag to pan':'Drag to orbit'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'2,234'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  {reading&&chapter&&author&&<Reader url={chapterUrl(reading.work,reading.file)} onTerm={onTerm} onNavigate={onNavigate} header={<div className="reader-head">
   <div className="eyebrow">{author.name} · {reading.work.title}</div>
   <h2>{chapter.title}</h2>{chapter.subtitle&&<p className="reader-subtitle">{chapter.subtitle}</p>}
   <div className="reader-nav"><Button variant="ghost" aria-label="Previous chapter" disabled={chapterIndex<=0} onClick={()=>go(-1)}><ChevronLeft size={16}/></Button><Button variant="ghost" aria-label="Next chapter" disabled={chapterIndex>=reading.work.chapters.length-1} onClick={()=>go(1)}><ChevronRight size={16}/></Button><Button variant="ghost" aria-label="Close the text" onClick={closeReader}><X size={16}/></Button></div>
   {lesson&&!focusNote&&<div className="lesson-focus">{(['primary','secondary'] as const).map(role=>{const names=lesson.focus.filter(f=>f.role===role).flatMap(f=>f.concepts);return names.length?<div className="focus-row" key={role}><span className={`focus-dot ${role}`}/><b>{names.join(', ')}</b></div>:null;})}<p>{lesson.theme}</p></div>}
   {focusNote&&(()=>{const c=focusNote.concepts.find(x=>classical(x.name))??focusNote.concepts[0];const sys=parts.get(c.elements[0])?.system??'connective';const note=classical(c.name);return <div className="juxta"><div className="juxta-title"><span>{focusNote.term}</span><span className="small-number">{c.name}{focusNote.concepts.length>1?` +${focusNote.concepts.length-1}`:''}</span><div className="juxta-actions"><Button variant="ghost" onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={13}/>{state.isolate?'Show body':'Isolate'}</Button><Button variant="ghost" onClick={()=>{setFocusNote(null);if(lesson)applyLesson(lesson);else setState(s=>({...s,selected:[],secondary:[],isolate:false}));}}>Back</Button></div></div><div className="juxta-col modern"><h4>Modern anatomy</h4><p>{explanation(c.name,sys)}</p></div><div className="juxta-col classical"><h4>Classical view</h4>{note&&(note.faculty||note.temperament)&&<div className="chips">{note.faculty&&<span>{note.faculty}</span>}{note.temperament&&<span>{note.temperament}</span>}</div>}<p>{note?.note??'No classical note has been written for this structure yet.'}</p></div></div>;})()}
  </div>}/>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?.name}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}{chosenNote&&<div className="classical-note"><span className="eyebrow">CLASSICAL VIEW</span>{(chosenNote.faculty||chosenNote.temperament)&&<div className="chips">{chosenNote.faculty&&<span>{chosenNote.faculty}</span>}{chosenNote.temperament&&<span>{chosenNote.temperament}</span>}</div>}<p>{chosenNote.note}</p></div>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],secondary:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">ABOUT ADAM</div><SheetTitle className="structure-title">The body the physicians wrote about.</SheetTitle><SheetDescription>Read Maimonides, Hippocrates, Galen and Avicenna with the structures they discuss lit up on a 3D human body.</SheetDescription><div className="about-copy"><p><strong>How to study</strong><br/>Open <em>Study</em>, choose a work and a chapter. Chapters mapped to the body highlight the organ under discussion in teal and related anatomy in amber. In the text, every anatomical term is live: tap it to see the structure and to read the modern description beside the classical understanding of the same organ.</p><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy. Named concepts can contain multiple pieces; each source mesh is rendered once. Geometry is simplified for the web.</p><p>Classical notes summarise Galenic physiology as the medieval physicians used it. They are historical explanations for study, not medical advice. This is not a diagnostic or surgical tool.</p><h3>Source</h3><p>Adam is a fork of <a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">Human Atlas</a> by Chaz Shemag (MIT). Anatomy: BodyParts3D, © The Database Center for Life Science, CC Attribution 4.0 International. The study texts are kept outside the repository and load only from a local corpus.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
